### ISSUE TITLE
Error trying to install Fedena

### ISSUE THREAD

**Issue by mindaslab** [passion8/fedena-install#1]
Hi, I typed (on Ubuntu 12.04)

``` bash
curl https://raw.github.com/Passionate/fedena-install/master/install.sh | bash
```

and I got

``` bash
bash: line 1: syntax error near unexpected token `<'
bash: line 1: `<html><body>You are being <a href="https://raw.github.com/passion8/fedena-install/master/install.sh">redirected</a>.</body></html>'
```

Any help / tip

**Comment by passion8** [comment]
thanks for reminding me, i have corrected it https://github.com/passion8/fedena-install/commit/322126e263fd0474a30f912fe2958b2384de583c . it is happened because I have changed my username .

**Comment by mindaslab** [comment]
Cool will try again
